import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Poppins } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased p-5`}>
        <h3 className="mb-48">
          <ul className="flex gap-3">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/gallery">Gallery</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/contact">Contact</Link></li>
            <li><Link href="/blog">Blog</Link></li>
            <li><Link href="/posts">Posts</Link></li>
            <li><Link href="/another">Another</Link></li>
          </ul>
        </h3>
        {children}
        <footer className="mt-48"><p className={poppins.className}>This is Footer Option</p></footer>
      </body>
    </html>
  );
}
